import pyttsx
engine = pyttsx.init()
engine.say("Somebody once told me the world is gonna roll me")
engine.say("I ain't the sharpest tool in the shed")
engine.say("She was looking kind of dumb with her finger and her thumb")
engine.say("In the shape of an \"L\" on her forehead")
engine.say("Well the years start coming and they don't stop coming")
engine.say("Fed to the rules and I hit the ground")
engine.say("Didn't make sense not to live for fun")
engine.say("Your brain gets smart but your head gets dumb")
engine.say("So much to do so much to see")
engine.say("So what's wrong with taking the back streets")
engine.say("You'll never know if you don't go")
engine.say("You'll never shine if you don't glow")
engine.say("Hey now you're an All Star get your game on, go play")
engine.say("Hey now you're a Rock Star get the show on get paid")
engine.say("And all that glitters is gold")
engine.say("Only shooting stars break the mold")
engine.say("It's a cool place and they say it gets colder")
engine.say("You're bundled up now but wait 'til you get older")
engine.say("But the meteor men beg to differ")
engine.say("Judging by the hole in the satellite picture")
engine.say("The ice we skate is getting pretty thin")
engine.say("The water's getting warm so you might as well swim")
engine.say("My world's on fire how about yours")
engine.say("That's the way I like it and I never get bored")
engine.say("Hey now you're an All Star get your game on, go play")
engine.say("Hey now you're a Rock Star get the show on get paid")
engine.say("And all that glitters is gold")
engine.say("Only shooting stars break the mold")
engine.say("Somebody once asked could I spare some change for gas")
engine.say("I need to get myself away from this place")
engine.say("I said yep what a concept")
engine.say("I could use a little fuel myself")
engine.say("And we could all use a little change")
engine.say("Well, the years start coming and they don't stop coming")
engine.say("Fed to the rules and I hit the ground running")
engine.say("Didn't make sense not to live for fun")
engine.say("Your brain gets smart but your head gets dumb")
engine.say("So much to do, so much to see")
engine.say("So what's wrong with taking the back streets")
engine.say("You'll never know if you don't go")
engine.say("You'll never shine if you don't glow")
engine.say("Hey now you're an All Star get your game on, go play")
engine.say("Hey now you're a Rock Star get the show on get paid")
engine.say("And all that glitters is gold")
engine.say("Only shooting stars break the mold")
engine.runAndWait()